# Generated by Django 6.0.3 on 2026-03-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='userchallenges',
            options={'verbose_name_plural': 'User Challenges'},
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='interests',
        ),
    ]
