# Generated by Django 6.0.2 on 2026-04-10 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenges_completed_challenges_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='completed',
        ),
        migrations.AddField(
            model_name='userchallenges',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
