# Generated by Django 6.0.2 on 2026-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenges_completed_userchallenges_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenges',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
