# Generated by Django 6.0.2 on 2026-04-19 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_userchallenges_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userchallenges',
            constraint=models.UniqueConstraint(fields=('user', 'challenge', 'date'), name='unique_user_challenge_per_day'),
        ),
    ]
