# Generated by Django 6.0.3 on 2026-04-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_userchallenges_unique_user_challenge_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='date',
        ),
    ]
