# Generated by Django 6.0.3 on 2026-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_remove_challenges_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
