# Generated by Django 6.0.2 on 2026-04-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendship_delete_challenges_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
